
version: '3'
services:
  packet-analyzer:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: packetdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
